#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VARIABLES_FILE="${SCRIPT_DIR}/variables.sh"

# Reset variables file
cat > "$VARIABLES_FILE" <<'HEADER'
#!/usr/bin/env bash
# Source this file to restore environment variables from a previous session:
#   source ./variables.sh
#
# This file is auto-generated by startup.sh — do not edit manually.
HEADER

# Helper: export a variable and persist it to variables.sh
save_var() {
  local name="$1" value="$2"
  export "$name=$value"
  echo "export ${name}=\"${value}\"" >> "$VARIABLES_FILE"
  echo "  ${name}=${value}"
}

echo "==> Creating Key Pair"
aws ec2 delete-key-pair --key-name ederaon-key 2>/dev/null || true
rm -f "${SCRIPT_DIR}/ederaon-key.pem"
aws ec2 create-key-pair \
  --key-name ederaon-key \
  --query 'KeyMaterial' \
  --output text > "${SCRIPT_DIR}/ederaon-key.pem"
chmod 400 "${SCRIPT_DIR}/ederaon-key.pem"

echo "==> Creating VPC"
VPC_ID=$(aws ec2 create-vpc \
  --cidr-block 10.0.0.0/16 \
  --query 'Vpc.VpcId' \
  --output text)
save_var VPC_ID "$VPC_ID"

aws ec2 create-tags --resources "$VPC_ID" \
  --tags Key=Name,Value=ederaon-vpc
aws ec2 modify-vpc-attribute --vpc-id "$VPC_ID" --enable-dns-hostnames

echo "==> Creating Subnet"
SUBNET_ID=$(aws ec2 create-subnet \
  --vpc-id "$VPC_ID" \
  --cidr-block 10.0.1.0/24 \
  --query 'Subnet.SubnetId' \
  --output text)
save_var SUBNET_ID "$SUBNET_ID"

aws ec2 create-tags --resources "$SUBNET_ID" \
  --tags Key=Name,Value=ederaon-subnet
aws ec2 modify-subnet-attribute --subnet-id "$SUBNET_ID" \
  --map-public-ip-on-launch

echo "==> Creating Internet Gateway"
IGW_ID=$(aws ec2 create-internet-gateway \
  --query 'InternetGateway.InternetGatewayId' \
  --output text)
save_var IGW_ID "$IGW_ID"

aws ec2 create-tags --resources "$IGW_ID" \
  --tags Key=Name,Value=ederaon-igw
aws ec2 attach-internet-gateway --internet-gateway-id "$IGW_ID" --vpc-id "$VPC_ID"

echo "==> Configuring Route Table"
RTB_ID=$(aws ec2 describe-route-tables \
  --filters Name=vpc-id,Values="$VPC_ID" \
  --query 'RouteTables[0].RouteTableId' \
  --output text)
save_var RTB_ID "$RTB_ID"

aws ec2 create-route --route-table-id "$RTB_ID" \
  --destination-cidr-block 0.0.0.0/0 \
  --gateway-id "$IGW_ID"

echo "==> Creating Security Group"
SG_ID=$(aws ec2 create-security-group \
  --group-name ederaon-sg \
  --description "EderaON test - SSH only" \
  --vpc-id "$VPC_ID" \
  --query 'GroupId' \
  --output text)
save_var SG_ID "$SG_ID"

MY_IP=$(curl -sf https://checkip.amazonaws.com) || {
  echo "ERROR: Failed to detect public IP from checkip.amazonaws.com" >&2
  echo "       Check your internet connection and try again." >&2
  exit 1
}

if ! [[ "${MY_IP}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "ERROR: Invalid IP address detected: '${MY_IP}'" >&2
  echo "       Expected a valid IPv4 address from checkip.amazonaws.com" >&2
  exit 1
fi
save_var MY_IP "$MY_IP"

aws ec2 authorize-security-group-ingress \
  --group-id "$SG_ID" \
  --protocol tcp \
  --port 22 \
  --cidr "${MY_IP}/32"

echo "==> Resolving latest Ubuntu 24.04 AMI..."
AMI_ID=$(aws ec2 describe-images \
  --owners 099720109477 \
  --filters "Name=name,Values=ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*" \
  --query 'sort_by(Images, &CreationDate)[-1].ImageId' \
  --output text)

if [[ -z "${AMI_ID}" || "${AMI_ID}" == "None" ]]; then
  echo "ERROR: Could not resolve Ubuntu 24.04 AMI in current region." >&2
  echo "       Verify your AWS region supports Ubuntu Noble images." >&2
  exit 1
fi
save_var AMI_ID "$AMI_ID"

echo "==> Launching Instance (AMI: ${AMI_ID})"
INSTANCE_ID=$(aws ec2 run-instances \
  --image-id "$AMI_ID" \
  --instance-type m5.large \
  --key-name ederaon-key \
  --security-group-ids "$SG_ID" \
  --subnet-id "$SUBNET_ID" \
  --block-device-mappings 'DeviceName=/dev/sda1,Ebs={VolumeSize=30,VolumeType=gp3}' \
  --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=ederaon-test}]' \
  --query 'Instances[0].InstanceId' \
  --output text)
save_var INSTANCE_ID "$INSTANCE_ID"

echo "==> Waiting for instance to be running..."
aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"

PUBLIC_IP=$(aws ec2 describe-instances \
  --instance-ids "$INSTANCE_ID" \
  --query 'Reservations[0].Instances[0].PublicIpAddress' \
  --output text)
if [[ -z "${PUBLIC_IP}" || "${PUBLIC_IP}" == "None" ]]; then
  echo "ERROR: Instance ${INSTANCE_ID} did not receive a public IP address." >&2
  echo "       Check subnet settings and VPC internet gateway configuration." >&2
  exit 1
fi
save_var PUBLIC_IP "$PUBLIC_IP"

SSH_KEY="${SCRIPT_DIR}/ederaon-key.pem"
SSH_OPTS=(-i "${SSH_KEY}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5)

echo "==> Waiting for SSH to become available..."
MAX_ATTEMPTS=30
ATTEMPT=0
until ssh "${SSH_OPTS[@]}" "ubuntu@${PUBLIC_IP}" true 2>/dev/null; do
  ATTEMPT=$((ATTEMPT + 1))
  if [ "$ATTEMPT" -ge "$MAX_ATTEMPTS" ]; then
    echo "ERROR: SSH not available after ${MAX_ATTEMPTS} attempts." >&2
    echo "       Last SSH error:" >&2
    timeout 10 ssh "${SSH_OPTS[@]}" "ubuntu@${PUBLIC_IP}" true 2>&1 || true
    exit 1
  fi
  if (( ATTEMPT % 5 == 0 )); then
    echo "    Attempt ${ATTEMPT}/${MAX_ATTEMPTS} — SSH error:"
    timeout 10 ssh "${SSH_OPTS[@]}" "ubuntu@${PUBLIC_IP}" true 2>&1 || true
  else
    echo "    Attempt ${ATTEMPT}/${MAX_ATTEMPTS} — retrying in 10s..."
  fi
  sleep 10
done

echo "==> Installing Docker and nftables on remote instance..."
ssh "${SSH_OPTS[@]}" "ubuntu@${PUBLIC_IP}" <<'REMOTE'
set -euo pipefail

# Wait for cloud-init to finish so apt locks are released
cloud-init status --wait

sudo apt-get update && sudo apt-get install -y docker.io nftables
sudo systemctl start docker
sudo usermod -aG docker ubuntu
REMOTE

REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CONNECT_SCRIPT="${REPO_ROOT}/connect.sh"

echo "==> Generating connect.sh"
cat > "$CONNECT_SCRIPT" <<EOF
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
  -i "\${SCRIPT_DIR}/scripts/aws/ederaon-key.pem" ubuntu@${PUBLIC_IP}
EOF
chmod +x "$CONNECT_SCRIPT"

echo ""
echo "==> Setup complete!"
echo "    Variables saved to: ${VARIABLES_FILE}"
echo ""
echo "    Connect: ./connect.sh"
echo ""
echo "    To restore variables in a new shell:"
echo "      source ${VARIABLES_FILE}"
echo ""
echo "    Docker is installed — reconnect SSH to pick up the docker group:"
echo "      ./connect.sh"
